spring.application.name=reservation
spring.data.mongodb.database=${env.MONGO_DATABASE}
spring.data.mongodb.uri=mongodb+srv://${env.MONGO_USER}:${env.MONGO_PASSWORD}@${env.MONGO_CLUSTER}.qjncsda.mongodb.net/?appName=${env.MONGO_CLUSTER}

# JWT Configuration
jwt.secret=${env.JWT_SECRET:defaultSecretKeyThatShouldBeAtLeast256BitsLongForSecurity}
jwt.expiration=${env.JWT_EXPIRATION:315360000000}
