spring.application.name=reservation

spring.mongodb.database=${MONGO_DATABASE}
spring.mongodb.uri=mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_CLUSTER}.qjncsda.mongodb.net/?appName=${MONGO_CLUSTER}

# JWT Configuration
jwt.secret=${JWT_SECRET:defaultSecretKeyThatShouldBeAtLeast256BitsLongForSecurity}
jwt.expiration=${JWT_EXPIRATION:315360000000}

server.port=${PORT:8080}